"""initial schema

Revision ID: 44b30f32f373
Revises: 
Create Date: 2026-02-19 16:37:37.168163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b30f32f373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('provider_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_settings_provider_name'), 'provider_settings', ['provider_name'], unique=True)
    op.create_table('sync_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_key'), 'user_preferences', ['key'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_user_edited', sa.Boolean(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('include_in_allocation', sa.Boolean(), nullable=False),
    sa.Column('assigned_asset_class_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('balance_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_asset_class_id'], ['asset_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'external_id', name='uix_provider_external_id')
    )
    op.create_table('securities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('manual_asset_class_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manual_asset_class_id'], ['asset_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('sync_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_session_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('accounts_synced', sa.Integer(), nullable=True),
    sa.Column('accounts_stale', sa.Integer(), nullable=True),
    sa.Column('accounts_error', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('sync_session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sync_session_id'], ['sync_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'sync_session_id', name='uix_account_sync_session')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('units', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_modified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'account_id', 'external_id', name='uix_activity_provider_account_external')
    )
    op.create_table('daily_holding_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('account_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['account_snapshot_id'], ['account_snapshots.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valuation_date', 'account_id', 'security_id', name='uix_daily_holding_value')
    )
    op.create_index(op.f('ix_daily_holding_values_account_id'), 'daily_holding_values', ['account_id'], unique=False)
    op.create_index(op.f('ix_daily_holding_values_account_snapshot_id'), 'daily_holding_values', ['account_snapshot_id'], unique=False)
    op.create_index(op.f('ix_daily_holding_values_security_id'), 'daily_holding_values', ['security_id'], unique=False)
    op.create_index(op.f('ix_daily_holding_values_valuation_date'), 'daily_holding_values', ['valuation_date'], unique=False)
    op.create_table('holding_lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('cost_basis_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('original_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('cost_basis_per_unit >= 0', name='ck_holding_lot_cost_basis_non_negative'),
    sa.CheckConstraint('current_quantity >= 0', name='ck_holding_lot_current_quantity_non_negative'),
    sa.CheckConstraint('original_quantity > 0', name='ck_holding_lot_original_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_lots_account_id'), 'holding_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_holding_lots_is_closed'), 'holding_lots', ['is_closed'], unique=False)
    op.create_index(op.f('ix_holding_lots_security_id'), 'holding_lots', ['security_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('snapshot_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('snapshot_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_snapshot_id'], ['account_snapshots.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_snapshot_id', 'security_id', name='uix_holding_snapshot_security')
    )
    op.create_index(op.f('ix_holdings_account_snapshot_id'), 'holdings', ['account_snapshot_id'], unique=False)
    op.create_index(op.f('ix_holdings_security_id'), 'holdings', ['security_id'], unique=False)
    op.create_table('lot_disposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('holding_lot_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('security_id', sa.String(length=36), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('proceeds_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=True),
    sa.Column('disposal_group_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('proceeds_per_unit >= 0', name='ck_lot_disposal_proceeds_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_lot_disposal_quantity_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['holding_lot_id'], ['holding_lots.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_disposals_account_id'), 'lot_disposals', ['account_id'], unique=False)
    op.create_index(op.f('ix_lot_disposals_disposal_group_id'), 'lot_disposals', ['disposal_group_id'], unique=False)
    op.create_index(op.f('ix_lot_disposals_holding_lot_id'), 'lot_disposals', ['holding_lot_id'], unique=False)
    op.create_index(op.f('ix_lot_disposals_security_id'), 'lot_disposals', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lot_disposals_security_id'), table_name='lot_disposals')
    op.drop_index(op.f('ix_lot_disposals_holding_lot_id'), table_name='lot_disposals')
    op.drop_index(op.f('ix_lot_disposals_disposal_group_id'), table_name='lot_disposals')
    op.drop_index(op.f('ix_lot_disposals_account_id'), table_name='lot_disposals')
    op.drop_table('lot_disposals')
    op.drop_index(op.f('ix_holdings_security_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_snapshot_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_holding_lots_security_id'), table_name='holding_lots')
    op.drop_index(op.f('ix_holding_lots_is_closed'), table_name='holding_lots')
    op.drop_index(op.f('ix_holding_lots_account_id'), table_name='holding_lots')
    op.drop_table('holding_lots')
    op.drop_index(op.f('ix_daily_holding_values_valuation_date'), table_name='daily_holding_values')
    op.drop_index(op.f('ix_daily_holding_values_security_id'), table_name='daily_holding_values')
    op.drop_index(op.f('ix_daily_holding_values_account_snapshot_id'), table_name='daily_holding_values')
    op.drop_index(op.f('ix_daily_holding_values_account_id'), table_name='daily_holding_values')
    op.drop_table('daily_holding_values')
    op.drop_table('activities')
    op.drop_table('account_snapshots')
    op.drop_table('sync_log_entries')
    op.drop_table('securities')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_user_preferences_key'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('sync_sessions')
    op.drop_index(op.f('ix_provider_settings_provider_name'), table_name='provider_settings')
    op.drop_table('provider_settings')
    op.drop_table('asset_classes')
    # ### end Alembic commands ###
